name: Hello World
author: Testing
description: Some description
inputs:
  who-to-greet:
    description: 'Who to gree'
    required: true
    default: 'Jane'
outputs:
  time:
    description: 'The greeting time!'

runs:
  using: 'docker'
  image: 'Dockerfile'
  # env:
  # entrypoint:
  args:
    - ${{inputs.who-to-greet}}
